### ISSUE TITLE
Dudley and Oro crouch and uncrouch repeatedly when set to crouch

### ISSUE THREAD

**Issue by rsnoob35** [Grouflon/3rd_training_lua#1] opened 2020-02-08 19:30 UTC
Dudley presses down every other frame, Oro presses down for 1 frame and returns to neutral for 4 frames. All other characters behave as expected.

This issue goes away when the characters are in hit/blockstun or have been dizzied

**Comment by Grouflon** [comment] 2020-02-10 19:38
Hey ! Thank you so much for your feedback, I'm really glad to know that some people out there are interested in this project :)

The issue is fixed on the dev branch and will be integrated into main branch for the next version (v0.4).
You can grab the dev branch if you want to try the last updates.

**Closed** 2020-02-10 20:07 UTC
