### ISSUE TITLE
Large issue : P2 cannot do EX moves even if they have meter

### ISSUE THREAD

**Issue by Shodokan** [Grouflon/3rd_training_lua#17] opened 2020-06-01 19:41 UTC
Regardless of if you are recording, manually inputting with keyboard or having it done as an auto-choice after being hit/blocking.

I got it to work once for a video I made a few days ago, but outside of that I can't get it to work.

It will work at the beginning when i first load the script if done as a response to block/hit from attack. But as soon as i try to modify anything by recording it no-longer will react with EX move.  It cannot do EX on record no matter what I try.

When this happens I cannot input fireball motions going towards opponent even with keyboard after the fact.  I can do 623, 214 motions but not 236.

This is 100% present in the current master version.  I thought this was fixed in previous version?

Video examples:
https://streamable.com/aucbg1 (using fork from boredkittenz)
https://streamable.com/05pw5i (2nd half is using master version here with no weighting)

Edit: I tested version 4 and 5 and it is present in both of these versions as well.

**Comment by Grouflon** [comment] 2020-11-09 13:10
I think this bug is also caused by the issue mentioned in this ticket https://github.com/Grouflon/3rd_training_lua/issues/18

**Comment by Grouflon** [comment] 2020-11-12 17:56
The last version is out, it should be fixed with the last version of fightcade. Can you test on your side and confirm me that it's gone ?

**Closed** 2020-11-13 13:11 UTC
